### ISSUE TITLE
Stop pluaralizing for a user

### ISSUE THREAD

**Issue by MSabherwal** [derekdowling/jsh-api#12]
When a new resource is created, it takes input as the singular form of a resource and tries to pluralize, ie a /users route would take "user" string to generate. This is highly error prone and unwieldy, as many words don't pluralize with an 's', and forcing the system to figure it out is fundamentally too magical, and likely unnecessary.

For example, what happens if instead of /users I wanted a /people route? I'd enter 'person' and get /persons.

Thoughts?

**Comment by derekdowling** [comment]
I intentionally didn't bother making the pluralization smarter because I wasn't sure how big of an issue it might be. After doing some digging to see if there was a definitive answer in the spec I found:

```
Note: This spec is agnostic about inflection rules, so the value of type can be either plural or singular. However, the same value should be used consistently throughout an implementation.
```

I will pull this bit of logic out when I get a chance unless you'd like to do that proactively.
